---
Resources:
  GpuInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-a58d0dc5
      InstanceType: p2.xlarge
      KeyName: selfie-art
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue VPCDefaultAppTabPublicSubnet
          GroupSet:
            - !ImportValue VPCDefaultPublicAppTabSecGroup
