---
Resources:
  GpuSpotInstance:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt [InstanceRole, Arn]
        SpotPrice: .4
        TargetCapacity: 1
        LaunchSpecifications:
          - InstanceType: p2.xlarge
            ImageId: ami-a58d0dc5
            KeyName: selfie-art
            BlockDeviceMappings:
              - DeviceName: /dev/sda1
                Ebs:
                  VolumeSize: 50
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeviceIndex: 0
                SubnetId: !ImportValue VPCDefaultAppTabPublicSubnet
                Groups:
                  - !ImportValue VPCDefaultPublicAppTabSecGroup
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - spotfleet.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EC2PowerUser
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
        - PolicyName: GenericIamUser
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:ListRoles
                  - iam:ListInstanceProfiles
                Resource: "*"
