---
Resources:
  GpuSpotInstance:
    Type: "AWS::EC2::SpotFleet"
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt [SpotfleetRole, Arn]
        SpotPrice: 1.6
        TargetCapacity: 1
        LaunchSpecifications:
          - InstanceType: p2.8xlarge
            ImageId: ami-a58d0dc5
            KeyName: selfie-art
            IamInstanceProfile:
              Arn: !GetAtt [InstanceProfile, Arn]
            BlockDeviceMappings:
              - DeviceName: /dev/sda1
                Ebs:
                  VolumeSize: 50
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeviceIndex: 0
                SubnetId: !ImportValue VPCDefaultAppTabPublicSubnet2b
                Groups:
                  - !ImportValue VPCDefaultPublicAppTabSecGroup
  SpotfleetRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - spotfleet.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EC2PowerUser
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
        - PolicyName: GenericIamUser
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:ListRoles
                  - iam:ListInstanceProfiles
                Resource: "*"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref InstanceRole
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - "arn:aws:s3:::warren-datasets"